### ISSUE TITLE
USD values shown do not reflect current market value

### ISSUE THREAD

**Issue by StevenJNPearce** [MyBitFoundation/MyBit-DDF.website#173]
As a developer, I would like to see the USD values on tasks reflect the current value of MYB token.
Example: "Develop payroll dApp" shows a value of $2,952.00, at today's prices the correct value is around $1360.00

**Comment by cryptnotiq** [comment]
thanks for sharing this, we are looking into it. @StevenJNPearce

**Comment by csmartinsfct** [comment]
Hey @StevenJNPearce we've put a solution in place. We'll work on optimizing it but it should be good for now :)

Thanks for reporting the issue!
